### ISSUE TITLE
pip install fails on Python 2.7

### ISSUE THREAD

**Issue by ssteinerx** [django/asgi_redis#10]
(liveblog)$ pip install asgi_redis
Collecting asgi_redis
  Using cached asgi_redis-0.14.1-py2.py3-none-any.whl
Collecting msgpack-python (from asgi_redis)
  Using cached msgpack-python-0.4.8.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages/setuptools/__init__.py", line 13, in <module>
    from setuptools.extension import Extension
  File "/Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages/setuptools/extension.py", line 9, in <module>
    from .monkey import get_unpatched
  File "/Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages/setuptools/monkey.py", line 10, in <module>
    from . import msvc
  File "/Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages/setuptools/msvc.py", line 27, in <module>
    from . import monkey
ImportError: cannot import name monkey

(liveblog) $ python -V
Python 2.7.12

(liveblog) $pip list
pip (8.1.2)
setuptools (27.1.1)
wheel (0.29.0)

(liveblog)$ pip install --upgrade pip setuptools wheel
Requirement already up-to-date: pip in /Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages
Requirement already up-to-date: setuptools in /Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages
Requirement already up-to-date: wheel in /Users/ssteiner/.virtualenvs/liveblog/lib/python2.7/site-packages

**Comment by alex** [comment]
This is a bug in the latest setuptools: https://github.com/pypa/setuptools/issues/779

**Comment by ssteinerx** [comment]
@alex Thanks, how annoying!
