### ISSUE TITLE
asgiref.base_layer.BaseChannelLayer.ChannelFull

### ISSUE THREAD

**Issue by pritstift** [django/asgi_redis#22]
I am doing some pen testing on my machine with django_channels. I use asyncio in Python 3.5 to parse UDP packages and send data into the redis channel layer. I sent around 120 packages (nearly) at once and get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "udpreceiver/UDPserver.py", line 18, in send_to_redis
    channel_layer.send(channel=channel,message=message)
  File "/Users/sush/ownCloud/server/channel_server/channeled_server/lib/python3.5/site-packages/asgi_redis/core.py", line 103, in send
    raise self.ChannelFull
asgiref.base_layer.BaseChannelLayer.ChannelFull
Task exception was never retrieved
future: <Task finished coro=<send_to_redis() done, defined at udpreceiver/UDPserver.py:8> exception=ChannelFull()>
Traceback (most recent call last):
  File "/Users/sush/ownCloud/server/channel_server/channeled_server/lib/python3.5/site-packages/asgi_redis/core.py", line 98, in send
    args=[self.serialize(message), self.expiry, self.get_capacity(channel)],
  File "/Users/sush/ownCloud/server/channel_server/channeled_server/lib/python3.5/site-packages/redis/client.py", line 2694, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/Users/sush/ownCloud/server/channel_server/channeled_server/lib/python3.5/site-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/Users/sush/ownCloud/server/channel_server/channeled_server/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/sush/ownCloud/server/channel_server/channeled_server/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/Users/sush/ownCloud/server/channel_server/channeled_server/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: full
```

following versions are installed:

```
asgi-redis==0.13.1
asgiref==0.14.0
channels==0.17.2
daphne==0.14.3
Django==1.10.3
```

Any suggestions why this error occurs and what i can do about that?

**Comment by proofit404** [comment]
Please read about back-pressure concept in channels. You can increase capacity value for your channel installation so it will hold more messages. You can increase number of worker so channel messages will be  processed faster.

**Comment by pritstift** [comment]
Thanks for the hint. I will colse the issue for now and have a look at your suggestions.
