### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'socket_connect_timeout'

### ISSUE THREAD

**Issue by jpic** [django/asgi_redis#36]
Runworker fails to start with asgi_redis >= 1.1:

```
2017-04-03 15:08:39,237 - INFO - runworker - Using single-threaded worker.
2017-04-03 15:08:39,237 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-04-03 15:08:39,238 - INFO - worker - Listening on channels event, http.request, post-account-delete, post-stat-create, websocket.connect, websocket.disconnect, websocket.receive
Traceback (most recent call last):
  File "venv/bin/awesome", line 11, in <module>
    load_entry_point('awesome', 'console_scripts', 'awesome')() 
  File "src/awesome/manage.py", line 8, in main
    execute_from_command_line(sys.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "venv/lib/python2.7/site-packages/channels/management/commands/runworker.py", line 83, in handle
    worker.run()
  File "venv/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "venv/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "venv/lib/python2.7/site-packages/asgi_redis/core.py", line 188, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "venv/lib/python2.7/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "venv/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "venv/lib/python2.7/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "venv/lib/python2.7/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'socket_connect_timeout'
```

Os: ubuntu xenial or arch linux
Python: 2.7
Django: 1.10.6
Channels: 1.1
Daphne: 1.2.0
Asgi_redis: 1.1.0 or 1.2.1

This seems to be because [UnixDomainSocketConnection](https://github.com/andymccurdy/redis-py/blob/ba832c1e0a51fccfe91f86356f7b58c955c33c4e/redis/connection.py#L712) does not support socket_connect_timeout.

With asgi_redis 1.0 it works fine, because it doesn't expect every different redis backend to have the same constructor signature.

Perhaps we could replace RedisChannelLayer's constructor to support a connection kwargs dict instead of specific socket_* kwargs ?

**Comment by andrewgodwin** [comment]
Yes, if they have varying arguments, that makes sense. I'll make the change now.

**Comment by andrewgodwin** [comment]
Could you confirm that fix I just committed works for you?

**Comment by jpic** [comment]
Works for me, thanks !
